getgenv().GetService = function(service: string)
    return game:GetService(service)
end

HttpService = GetService("HttpService")
ReplicatedStorage = GetService("ReplicatedStorage")
RunService = GetService("RunService")
Players = GetService("Players")
MarketplaceService = GetService("MarketplaceService")
TweenService = GetService("TweenService")
CollectionService = GetService("CollectionService")
ReplicatedFirst = GetService("ReplicatedFirst")
TeleportService = GetService("TeleportService")
UserInputService = GetService("UserInputService")
SoundService = GetService("SoundService")
ProximityPromptService = GetService("ProximityPromptService")
GroupService = GetService("GroupService")
ContextActionService = GetService("ContextActionService")
StatsService = GetService("Stats")
StarterGui = GetService("StarterGui")
RbxAnalyticsService = GetService("RbxAnalyticsService")